version: '3.3'

networks:
  sonarnet:
    driver: bridge

services:
   postgres:
     container_name: postgres
     image: postgres:latest
     restart: always
     networks:
       - sonarnet
     ports:
       - 5432:5432
     volumes:
       - ./postgresql:/var/lib/postgresql
     environment:
       POSTGRES_PASSWORD: SonarQube
       POSTGRES_DB: SonarQube
   sonarqube:
     container_name: sonarqube
     image: sonarqube:alpine
     restart: always
     networks:
       - sonarnet
     ports:
       - 9000:9000
       - 9092:9092
     volumes:
       - ./sonarqube/conf:/opt/sonarqube/conf
       - ./sonarqube/data:/opt/sonarqube/data
       - ./sonarqube/extensions:/opt/sonarqube/extensions
       - ./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
     environment:
       SONARQUBE_JDBC_USERNAME: postgres
       SONARQUBE_JDBC_PASSWORD: SonarQube
       SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/SonarQube