version: '3.5'

networks:
  java:
    external: true
    name: java

services:
  app:
    container_name: app
    image: ibmjava:8-jre-alpine
    restart: always
    working_dir: /opt/app
    command: java -jar app.jar
    environment: 
      - TZ=Japan
    ports:
      - 9100:9000
    expose:
      - '9000'
    volumes:
      - .:/opt/app
    # depends_on:
    #   - keycloak
    networks:
      - java
