version: '3.3'

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    restart: always
    ports:
      - 8190:8080
    environment:
      KEYCLOAK_USER: tanghuan
      KEYCLOAK_PASSWORD: tanghuan
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    networks:
      - keycloak
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    networks:
      - keycloak

networks:
  keycloak:
