version: '3.5'

networks:
  its_fun:
    external: true
    name: its_fun

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.itsfun.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.itsfun.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'tanghuan@163.com'
        gitlab_rails['gitlab_email_display_name'] = '成都科鸿达'
        gitlab_rails['gitlab_email_reply_to'] = 'tanghuan@163.com'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.163.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "tanghuan@163.com"
        gitlab_rails['smtp_password'] = "*********"
        gitlab_rails['smtp_domain'] = "163.com"
        gitlab_rails['smtp_authentication'] = "login"
    expose:
      - '80'
      - '443'
    ports:
      - '2222:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - its_fun